// Declarative jenkinsfile - groovy syntax

pipeline {
    agent any
    stages {
        stage("checkout git"){
            steps {
                sh "echo 'checkout git'"
            }
        }
        stage("build and compile") {
            steps {
                sh "echo 'building the project'"
                sh "echo 'compiling the project'"
                sh "echo 'build and compile successful'"
            }
        }
        stage ("unit test"){
            steps {
                sh "echo 'running unit tests'"
                sh "ls -la"
                sh "echo 'unit tests successful'"
            }
        }
        stage ("deploy to staging") {
            steps {
                sh "echo 'deploying to staging environment'"
                sh "echo 'deployment successful'"
            }
        }
        stage ("deploy to production") {
            steps {
                sh "echo 'deploying to production environment'"
                sh "echo 'deployment successful'"
            }
        }
        stage ("notify team") {
            steps {
                sh "echo 'notifying the team about the deployment'"
                sh "echo 'notification sent successfully'"
            }
        }
}
}